/* Tyga Financials — desktop navigation mirror with reliable collapse/expand control. */
(() => {
  'use strict';
  if (window.innerWidth < 900 || document.getElementById('tygaDesktopNav')) return;
  const items=[['digits','⌁','Digits'],['signals','◈','Signals'],['news','◉','News'],['journal','▤','Journal'],['upgrade','◆','Upgrade'],['account','●','Account']];
  const style=document.createElement('style');style.textContent=`@media(min-width:900px){#tygaDesktopNav{position:fixed;right:18px;top:50%;transform:translateY(-50%);width:94px;z-index:9500;display:flex;flex-direction:column;gap:7px;padding:9px;border:1px solid rgba(94,160,255,.22);border-radius:22px;background:rgba(10,15,28,.92);backdrop-filter:blur(20px);box-shadow:0 18px 55px rgba(0,0,0,.38);transition:width .22s ease,padding .22s ease}#tygaDesktopNav .tdn-item{width:76px;min-height:64px;padding:7px 4px;border:1px solid transparent;border-radius:15px;background:transparent;color:#9AAAC4;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;font:700 10px system-ui;cursor:pointer;transition:.18s ease}#tygaDesktopNav .tdn-item .tdn-icon{font-size:20px;line-height:1;color:#7E8EA8}#tygaDesktopNav .tdn-item:hover{color:#F7FAFF;background:rgba(34,211,238,.07);border-color:rgba(34,211,238,.22);transform:translateX(-2px)}#tygaDesktopNav .tdn-item.active{color:#fff;background:linear-gradient(145deg,rgba(34,211,238,.18),rgba(167,139,250,.14));border-color:rgba(34,211,238,.42)}#tygaDesktopNav .tdn-item.active .tdn-icon{color:#22D3EE;text-shadow:0 0 14px rgba(34,211,238,.7)}#tygaDesktopNav .tdn-label{font-size:9px;letter-spacing:.04em}body{padding-right:130px!important;transition:padding-right .22s ease}#tygaDesktopNav:before{content:'TYGA';position:absolute;top:-31px;left:0;width:100%;text-align:center;color:#22D3EE;font:800 10px system-ui;letter-spacing:.18em}#tygaDesktopNav .tdn-toggle{position:absolute;right:-12px;top:-12px;width:30px;height:30px;border:1px solid rgba(34,211,238,.4);border-radius:50%;background:#0b1424;color:#22D3EE;display:flex;align-items:center;justify-content:center;font:900 16px system-ui;cursor:pointer;box-shadow:0 5px 18px rgba(0,0,0,.4);z-index:2}#tygaDesktopNav .tdn-toggle:hover{background:#12233c;transform:scale(1.05)}#tygaDesktopNav.is-collapsed{width:42px;padding:7px 5px;gap:4px}#tygaDesktopNav.is-collapsed .tdn-item{width:32px;min-height:38px;padding:4px;border-radius:10px}#tygaDesktopNav.is-collapsed .tdn-label,#tygaDesktopNav.is-collapsed:before{display:none}#tygaDesktopNav.is-collapsed .tdn-item .tdn-icon{font-size:16px}body.tyga-nav-collapsed{padding-right:74px!important}}`;document.head.appendChild(style);
  const nav=document.createElement('aside');nav.id='tygaDesktopNav';nav.setAttribute('aria-label','Tyga Financials navigation');
  const toggle=document.createElement('button');toggle.className='tdn-toggle';toggle.type='button';toggle.setAttribute('aria-label','Collapse navigation');toggle.title='Collapse navigation';toggle.textContent='›';nav.appendChild(toggle);
  items.forEach(([key,icon,label])=>{const b=document.createElement('button');b.className='tdn-item';b.dataset.section=key;b.innerHTML=`<span class="tdn-icon">${icon}</span><span class="tdn-label">${label}</span>`;b.addEventListener('click',()=>activate(key));nav.appendChild(b)});document.body.appendChild(nav);
  function setCollapsed(v){nav.classList.toggle('is-collapsed',v);document.body.classList.toggle('tyga-nav-collapsed',v);toggle.textContent=v?'‹':'›';toggle.setAttribute('aria-label',v?'Expand navigation':'Collapse navigation');toggle.title=v?'Expand navigation':'Collapse navigation';try{localStorage.setItem('tygaDesktopNavCollapsed',v?'1':'0')}catch(e){}}
  let saved=false;try{saved=localStorage.getItem('tygaDesktopNavCollapsed')==='1'}catch(e){}setCollapsed(saved);toggle.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setCollapsed(!nav.classList.contains('is-collapsed'))});
  function allSections(){return [...document.querySelectorAll('section,main > div,[id*="screen"],[id*="view"],[id*="panel"],[id*="page"]')]}const patterns={digits:/digits|digit|volatility|tick/i,signals:/signals?|signal|forecast|analysis/i,news:/news|market news/i,journal:/journal|trade journal|history/i,upgrade:/upgrade|auto.?execute|deriv|automation/i,account:/account|profile|settings/i};
  function activate(key){document.querySelectorAll('#tygaDesktopNav .tdn-item').forEach(x=>x.classList.toggle('active',x.dataset.section===key));const matches=allSections().filter(el=>patterns[key].test((el.id||'')+' '+(el.className||'')+' '+(el.getAttribute('aria-label')||'')+' '+(el.innerText||'').slice(0,300)));const target=matches.find(el=>el.offsetParent!==null)||matches[0];if(target){target.scrollIntoView({behavior:'smooth',block:'start'});return}const trigger=[...document.querySelectorAll('button,a,[role="tab"]')].find(el=>patterns[key].test((el.innerText||'')+' '+(el.getAttribute('aria-label')||'')));if(trigger)trigger.click()}
  const sync=()=>{const y=scrollY+innerHeight*.35;let best='signals',bestTop=Infinity;for(const [key,re] of Object.entries(patterns))for(const el of allSections()){if(re.test((el.id||'')+' '+(el.className||'')+' '+(el.innerText||'').slice(0,250))){const top=Math.abs(el.getBoundingClientRect().top+scrollY-y);if(top<bestTop){bestTop=top;best=key}}}document.querySelectorAll('#tygaDesktopNav .tdn-item').forEach(x=>x.classList.toggle('active',x.dataset.section===best))};window.addEventListener('scroll',sync,{passive:true});sync();
})();
