/* Tyga Financials — execution safety bridge. */
(() => {
  'use strict';
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();
  const notify=msg=>{try{if(typeof showToast==='function')showToast(msg);else console.warn('[Tyga]',msg)}catch(_){console.warn('[Tyga]',msg)}};
  const ex=()=>typeof derivExec!=='undefined'?derivExec:null;
  const acct=()=>typeof accountSettings!=='undefined'?accountSettings:null;
  const selectedBalance=()=>{const o=document.getElementById('dtAccountSelect')?.selectedOptions?.[0];const n=Number(o?.dataset?.balance);if(Number.isFinite(n)&&n>0)return n;const t=o?.textContent||'';const m=t.match(/(?:USD|EUR|GBP|AUD|CAD|BTC|ETH)?\s*([0-9]+(?:[.,][0-9]+)?)\s*$/i);return m?Number(m[1].replace(/,/g,'')):NaN};
  const currentBalance=()=>{const e=ex(),a=acct();for(const v of [e?.accountInfo?.balance,e?.balance,a?.balance,a?.accountBalance,selectedBalance(),window.tygaDemoBalance]){const n=Number(v);if(Number.isFinite(n)&&n>0)return n}return null};
  function removeWhatsApp(){[...document.querySelectorAll('.section-label,.acct-card')].forEach(el=>{const t=(el.innerText||'').toLowerCase();if(t.includes('whatsapp alerts')||t.includes('callmebot')){const p=el.previousElementSibling;el.remove();if(p&&/whatsapp alerts/i.test(p.innerText||''))p.remove()}});window.sendWhatsApp=()=>{}};
  function gate(stake,forceLive){if(!window.TygaRisk)return{ok:false,reason:'Trading safety module is not loaded.'};return window.TygaRisk.canTrade({stake:Number(stake)||0,balance:forceLive?null:currentBalance(),forceLive:!!forceLive})}
  function installAutoGate(){if(typeof window.executeAutoTrade!=='function'||window.executeAutoTrade.__tygaGuarded)return false;const original=window.executeAutoTrade;function guarded(call,sym,riskAmt){const e=ex(),live=!!(e&&e.accountInfo&&!e.accountInfo.is_virtual),result=gate(Math.max(Number(riskAmt)||0,0.35),live);if(!result.ok){notify('🛡 Trade blocked: '+result.reason);return false}return original.apply(this,arguments)}guarded.__tygaGuarded=true;window.executeAutoTrade=guarded;return true}
  function installDigitGate(){const btn=document.getElementById('btnDigitTrade');if(!btn||btn.__tygaGuarded)return false;btn.addEventListener('click',e=>{const a=acct(),stake=Math.max((Number(a?.size)||0)*0.005,0.35),eState=ex(),live=!!(eState&&eState.accountInfo&&!eState.accountInfo.is_virtual),result=gate(stake,live);if(!result.ok){e.preventDefault();e.stopImmediatePropagation();notify('🛡 Digit trade blocked: '+result.reason)}},true);btn.__tygaGuarded=true;return true}
  function connectExecutionMode(){const toggle=document.getElementById('dtToggle');if(!toggle||toggle.__tygaModeGuarded)return false;toggle.addEventListener('click',()=>setTimeout(()=>{const e=ex();window.TygaRisk?.configure({mode:e?.enabled?'live':'paper'})},0),true);toggle.__tygaModeGuarded=true;return true}
  function wrapSettlement(){if(typeof window.handleContractUpdate!=='function'||window.handleContractUpdate.__tygaGuarded)return false;const original=window.handleContractUpdate;async function guarded(poc){const record=!!(poc?.is_sold&&typeof autoContracts!=='undefined'&&autoContracts[poc.contract_id]&&!autoContracts[poc.contract_id].settled);const result=await original.apply(this,arguments);if(record)window.TygaRisk?.recordTrade({pnl:Number(poc.profit)||0});return result}guarded.__tygaGuarded=true;window.handleContractUpdate=guarded;return true}
  function statusPanel(){if(document.getElementById('tygaRiskBadge'))return;const host=document.getElementById('view-upgrade')||document.getElementById('view-account');if(!host)return;const box=document.createElement('div');box.id='tygaRiskBadge';box.style='margin:12px 16px;padding:12px 14px;border-radius:12px;border:1px solid rgba(34,211,238,.28);background:rgba(34,211,238,.07);font:700 11px system-ui;color:var(--text)';box.innerHTML='<div style="color:var(--cyan);margin-bottom:5px">🛡 TYGA EXECUTION SAFETY</div><div id="tygaRiskText"></div>';host.prepend(box);const update=()=>{const r=window.TygaRisk?.settings?.(),t=document.getElementById('tygaRiskText');if(t&&r){const b=currentBalance();t.textContent=r.mode==='live'?`Mode: LIVE · Max stake $${r.maxStake}`:`Mode: PAPER · Max stake ${Number.isFinite(Number(b))?'$'+(b*.60).toFixed(2)+' (60% of $'+Number(b).toFixed(2)+')':'waiting for demo balance'} · Daily loss $${r.maxDailyLoss}`}};update();setInterval(update,2000)}
  function start(){removeWhatsApp();installAutoGate();installDigitGate();connectExecutionMode();wrapSettlement();statusPanel();const observer=new MutationObserver(()=>{removeWhatsApp();installAutoGate();installDigitGate();connectExecutionMode();wrapSettlement();statusPanel()});observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),20000)}
  ready(start);
})();
