// Tyga Financials — service worker.
const CACHE='tyga-shell-v21';
const SHELL_FILES=['./','./index.html','./manifest.json','./icon-192.png','./icon-512.png','./telegram.js','./deriv-fix.js','./desktop-ui.js','./desktop-nav.js','./desktop-workspace.js','./desktop-loader.js','./desktop-terminal.js','./trading-safety.js','./execution-guard.js','./deriv-config.js','./desktop-left-rail-fix.js','./trading-chart.js','./signal-integrity.js','./state-restore.js'];
const INJECT_TAGS='<script src="./state-restore.js?v=21"></script><script src="./deriv-config.js?v=21"></script><script src="./deriv-fix.js?v=21"></script><script src="./telegram.js?v=21" defer></script><script src="./desktop-ui.js?v=21" defer></script><script src="./desktop-nav.js?v=21" defer></script><script src="./desktop-workspace.js?v=21" defer></script><script src="./desktop-terminal.js?v=21" defer></script><script src="./trading-safety.js?v=21" defer></script><script src="./execution-guard.js?v=21" defer></script><script src="./desktop-left-rail-fix.js?v=21" defer></script><script src="./signal-integrity.js?v=21" defer></script><script src="./trading-chart.js?v=21" defer></script>';
async function shellResponse(request){const upstream=await fetch(request,{cache:'no-store'});if(!upstream.ok)return upstream;const type=upstream.headers.get('content-type')||'';if(!type.includes('text/html'))return upstream;let html=await upstream.text();html=html.replace(/<script[^>]+(?:state-restore|deriv-config|deriv-fix|telegram|desktop-ui|desktop-nav|desktop-workspace|desktop-terminal|trading-safety|execution-guard|desktop-left-rail-fix|signal-integrity|trading-chart)\.js[^>]*><\/script>/gi,'');html=html.replace(/<a\b[^>]*(?:whatsapp|wa\.me)[^>]*>[\s\S]*?<\/a>/gi,'');html=html.replace(/<button\b[^>]*(?:whatsapp|wa\.me)[^>]*>[\s\S]*?<\/button>/gi,'');html=html.replace(/<\/head>/i,`${INJECT_TAGS}</head>`);return new Response(html,{status:upstream.status,statusText:upstream.statusText,headers:new Headers(upstream.headers)})}
self.addEventListener('install',event=>{event.waitUntil((async()=>{const c=await caches.open(CACHE);await c.addAll(SHELL_FILES);try{await c.put('./index.html',await shellResponse(new Request('./index.html')))}catch(_){} })());self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim()});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const client of list)if('focus'in client)return client.focus();if(self.clients.openWindow)return self.clients.openWindow('./')}))});
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.pathname.endsWith('/index.html')||url.pathname.endsWith('/')){event.respondWith(shellResponse(req).then(async r=>{const c=await caches.open(CACHE);await c.put(req,r.clone()).catch(()=>{});return r}).catch(()=>caches.match(req)));return}event.respondWith(fetch(req).then(response=>{if(SHELL_FILES.some(f=>req.url.endsWith(f.replace('./','')))){const copy=response.clone();caches.open(CACHE).then(c=>c.put(req,copy)).catch(()=>{})}return response}).catch(()=>caches.match(req)))});
